- name: Install Helm
  shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm

- name: Add Cilium Helm repo
  shell: helm repo add cilium https://helm.cilium.io/

- name: Update Helm repos
  shell: helm repo update

- name: Install Cilium via Helm
  shell: |
    helm install cilium cilium/cilium --version 1.15.0 \
      --namespace kube-system \
      --set kubeProxyReplacement=strict \
      --set k8sServiceHost=192.168.56.10 \
      --set k8sServicePort=6443
  args:
    creates: /etc/cilium-installed
  register: cilium_out

- name: Mark Cilium as installed
  file:
    path: /etc/cilium-installed
    state: touch
