- name: Install containerd
  apt:
    name: containerd
    state: present
    update_cache: true

- name: Create containerd config
  shell: |
    mkdir -p /etc/containerd
    containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

- name: Restart containerd
  service:
    name: containerd
    enabled: yes
    state: restarted
