- name: Disable swap
  include_tasks: disable-swap.yml

- name: Install container runtime
  include_tasks: install-container-runtime.yml

- name: Install Kubernetes components
  include_tasks: install-kubernetes.yml

- name: Join node to cluster
  include_tasks: join-cluster.yml
