Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
  
    nodes = {
      "k8s-master" => { :ip => "192.168.56.10", :memory => 6144 },
      "k8s-worker1" => { :ip => "192.168.56.11", :memory => 12288 },
      "k8s-worker2" => { :ip => "192.168.56.12", :memory => 12288 }
    }
  
    nodes.each do |name, opts|
      config.vm.define name do |node|
        node.vm.hostname = name
        node.vm.network :private_network, ip: opts[:ip]
        node.vm.provider "virtualbox" do |vb|
          vb.memory = opts[:memory]
          vb.cpus = 2
        end
  
        node.vm.provision "shell", inline: <<-SHELL
          apt-get update
          apt-get install -y python3 python3-pip
        SHELL
      end
    end
  end
  